// 已发布的省页清单([slug] 路由与 sitemap 的事实源)。
// 发布新省 = 生成 lib/regions-data/<slug>.json + 此处加一条(数据生成见 data-hub 仓库 content-playbook)。

export const PUBLISHED_REGIONS = [
  { slug: "guangdong", zh: "广东", en: "Guangdong" },
  { slug: "jiangsu", zh: "江苏", en: "Jiangsu" },
  { slug: "zhejiang", zh: "浙江", en: "Zhejiang" },
  { slug: "shandong", zh: "山东", en: "Shandong" },
  { slug: "hebei", zh: "河北", en: "Hebei" },
  { slug: "henan", zh: "河南", en: "Henan" },
  { slug: "hubei", zh: "湖北", en: "Hubei" },
  { slug: "hunan", zh: "湖南", en: "Hunan" },
  { slug: "sichuan", zh: "四川", en: "Sichuan" },
  { slug: "fujian", zh: "福建", en: "Fujian" },
  { slug: "shanxi", zh: "山西", en: "Shanxi" },
  { slug: "neimenggu", zh: "内蒙古", en: "Inner Mongolia" },
  { slug: "liaoning", zh: "辽宁", en: "Liaoning" },
  { slug: "jilin", zh: "吉林", en: "Jilin" },
  { slug: "heilongjiang", zh: "黑龙江", en: "Heilongjiang" },
  { slug: "anhui", zh: "安徽", en: "Anhui" },
  { slug: "jiangxi", zh: "江西", en: "Jiangxi" },
  { slug: "guangxi", zh: "广西", en: "Guangxi" },
  { slug: "hainan", zh: "海南", en: "Hainan" },
  { slug: "guizhou", zh: "贵州", en: "Guizhou" },
  { slug: "yunnan", zh: "云南", en: "Yunnan" },
  { slug: "xizang", zh: "西藏", en: "Tibet (Xizang)" },
  { slug: "shaanxi", zh: "陕西", en: "Shaanxi" },
  { slug: "gansu", zh: "甘肃", en: "Gansu" },
  { slug: "qinghai", zh: "青海", en: "Qinghai" },
  { slug: "ningxia", zh: "宁夏", en: "Ningxia" },
  { slug: "xinjiang", zh: "新疆", en: "Xinjiang" },
  { slug: "municipalities", zh: "直辖市", en: "The Four Municipalities" },
];
